### PR TITLE
Update dependencies and code for Mbed TLS 2.27.0

### PR DESCRIPTION
**Pull request by moshe-shahar**
- `parsec-client` - `0.12.0` -> `0.13.0`
- `psa-crypto` - `0.8.0` -> `0.9.0`
- Fix compilation errors
- Update Travis CI to use Mbed TLS v2.27.0

Ref: [Mbed TLS v2.27.0](https://github.com/ARMmbed/mbedtls/releases/tag/v2.27.0)

### CODE REVIEW

**Comment by ionut-arm** [comment]
Seems that the CI is failing because the permissions for `ci.sh` were changed.

**Review by ionut-arm — COMMENTED** [review]
The newer version of `psa-crypto` uses Mbed TLS 3.0.0 underneath (it was updated in https://github.com/parallaxsecond/rust-psa-crypto/pull/88 ) so I'm not sure if this will work with 2.27.0, hopefully it does.

The ACL values on `ci.sh` still seem to have been modified

**Comment by ionut-arm** [comment]
Oh, the container where the integration tests are run has been changed, so the setup process for the TPM server in `ci.sh` should be a bit different. The new steps (taken from [here](https://github.com/parallaxsecond/parsec/blob/main/ci.sh#L156)):
```bash
cp /tmp/NVChip .
# Start and configure TPM server
tpm_server &
sleep 5
# Ownership has already been taken with "tpm_pass".
tpm2_startup -T mssim
```

**Comment by moshe-shahar** [comment]
Thank you @ionut-arm.
CI passed successfully.

**Review by hug-dev — APPROVED** [review]
Well, it worked with 2.27.0 so I guess we are good to go? Can make a new release after that PR.

**Review by ionut-arm — APPROVED** [review]
:+1:
